version: '3.8'

name: uf-geoplan-demo

services:
    webserver:
        image: nginx:latest
        container_name: "app-server-nginx"
        env_file:
            - .env
        depends_on:
            - database
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./app/dist:/app/public
        ports:
            - ${NGINX_PORT_IN}:${NGINX_PORT_OUT}
    rest-api:
        image: node:16
        container_name: "rest-api-express"
        env_file:
            - .env
        environment:
            NODE_ENV: ${NODE_ENV}
        command: bash -c "[ -d \"node_modules\" ] && npm run start || npm ci && npm run start"
        restart: unless-stopped
        user: node
        volumes:
            - ./rest/:/home/node/rest/
        working_dir: /home/node/rest/
        expose:
            - ${API_PORT}
        ports:
            - ${API_PORT}:${API_PORT}
    database:
        image: mariadb:latest
        container_name: "database-crash-mariadb"
        env_file:
            - .env
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        volumes:
            - dbdata:/var/lib/mysql
            - ./db/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
            - ./db/init_data:/docker-entrypoint-initdb.d/init_data
        expose:
            - ${MYSQL_PORT_IN}
volumes:
    dbdata: {}